// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TransportesOrellanaSpa.Api.Data;

#nullable disable

namespace TransportesOrellanaSpa.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260831172410_ExpandClienteDireccion")]
    partial class ExpandClienteDireccion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CamionConductor", b =>
                {
                    b.Property<int>("CamionId")
                        .HasColumnType("integer");

                    b.Property<int>("ConductorId")
                        .HasColumnType("integer");

                    b.HasKey("CamionId", "ConductorId");

                    b.HasIndex("ConductorId");

                    b.ToTable("CamionConductor");
                });

            modelBuilder.Entity("TransportesOrellanaSpa.Api.Models.Camion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Ano")
                        .HasColumnType("integer");

                    b.Property<string>("Caballos")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Capacidad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Cilindrada")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaPermisoCirculacion")
                        .HasColumnType("date");

                    b.Property<DateTime>("FechaRevisionTecnica")
                        .HasColumnType("date");

                    b.Property<DateTime>("FechaSeguroObligatorio")
                        .HasColumnType("date");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Motor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Patente")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("PermisoAlDia")
                        .HasColumnType("boolean");

                    b.Property<bool>("RevisionAlDia")
                        .HasColumnType("boolean");

                    b.Property<bool>("SeguroAlDia")
                        .HasColumnType("boolean");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Transmision")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Patente")
                        .IsUnique();

                    b.ToTable("Camiones");
                });

            modelBuilder.Entity("TransportesOrellanaSpa.Api.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Ciudad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Comuna")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Observaciones")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Rut")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Tarifa")
                        .HasColumnType("numeric");

                    b.Property<string>("TipoCarga")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Rut")
                        .IsUnique();

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("TransportesOrellanaSpa.Api.Models.Conductor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ApellidoMaterno")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ApellidoPaterno")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Edad")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaControlLicencia")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaIngreso")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("LicenciaAlDia")
                        .HasColumnType("boolean");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Rut")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TipoLicencia")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Rut")
                        .IsUnique();

                    b.ToTable("Conductores");
                });

            modelBuilder.Entity("TransportesOrellanaSpa.Api.Models.Remolque", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activa")
                        .HasColumnType("boolean");

                    b.Property<int>("Ano")
                        .HasColumnType("integer");

                    b.Property<int?>("CamionHabitualId")
                        .HasColumnType("integer");

                    b.Property<double>("CapacidadToneladas")
                        .HasColumnType("double precision");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Patente")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CamionHabitualId");

                    b.HasIndex("Patente")
                        .IsUnique();

                    b.ToTable("Remolques");
                });

            modelBuilder.Entity("TransportesOrellanaSpa.Api.Models.Viaje", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CamionId")
                        .HasColumnType("integer");

                    b.Property<int>("ClienteId")
                        .HasColumnType("integer");

                    b.Property<string>("ComunaDestino")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ComunaOrigen")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ConductorId")
                        .HasColumnType("integer");

                    b.Property<string>("Destino")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EstadoPago")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaPago")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("Kilometros")
                        .HasColumnType("double precision");

                    b.Property<string>("Observaciones")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Origen")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RemolqueId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Tarifa")
                        .HasColumnType("numeric");

                    b.Property<string>("TipoCarga")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CamionId");

                    b.HasIndex("ClienteId");

                    b.HasIndex("ConductorId");

                    b.HasIndex("RemolqueId");

                    b.ToTable("Viajes");
                });

            modelBuilder.Entity("CamionConductor", b =>
                {
                    b.HasOne("TransportesOrellanaSpa.Api.Models.Camion", null)
                        .WithMany()
                        .HasForeignKey("CamionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TransportesOrellanaSpa.Api.Models.Conductor", null)
                        .WithMany()
                        .HasForeignKey("ConductorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TransportesOrellanaSpa.Api.Models.Remolque", b =>
                {
                    b.HasOne("TransportesOrellanaSpa.Api.Models.Camion", "CamionHabitual")
                        .WithMany("Remolques")
                        .HasForeignKey("CamionHabitualId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CamionHabitual");
                });

            modelBuilder.Entity("TransportesOrellanaSpa.Api.Models.Viaje", b =>
                {
                    b.HasOne("TransportesOrellanaSpa.Api.Models.Camion", "Camion")
                        .WithMany("Viajes")
                        .HasForeignKey("CamionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TransportesOrellanaSpa.Api.Models.Cliente", "Cliente")
                        .WithMany("Viajes")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TransportesOrellanaSpa.Api.Models.Conductor", "Conductor")
                        .WithMany("Viajes")
                        .HasForeignKey("ConductorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TransportesOrellanaSpa.Api.Models.Remolque", "Remolque")
                        .WithMany("Viajes")
                        .HasForeignKey("RemolqueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Camion");

                    b.Navigation("Cliente");

                    b.Navigation("Conductor");

                    b.Navigation("Remolque");
                });

            modelBuilder.Entity("TransportesOrellanaSpa.Api.Models.Camion", b =>
                {
                    b.Navigation("Remolques");

                    b.Navigation("Viajes");
                });

            modelBuilder.Entity("TransportesOrellanaSpa.Api.Models.Cliente", b =>
                {
                    b.Navigation("Viajes");
                });

            modelBuilder.Entity("TransportesOrellanaSpa.Api.Models.Conductor", b =>
                {
                    b.Navigation("Viajes");
                });

            modelBuilder.Entity("TransportesOrellanaSpa.Api.Models.Remolque", b =>
                {
                    b.Navigation("Viajes");
                });
#pragma warning restore 612, 618
        }
    }
}
