using Microsoft.AspNetCore.Mvc;
using TransportesOrellanaSpa.Api.Models;

namespace TransportesOrellanaSpa.Api.Controllers;

[ApiController]
[Route("api/[controller]")]
public class CamionController : ControllerBase
{
    [HttpGet]
    public ActionResult<IEnumerable<Camion>> GetAll()
    {
        var Camiones = new List<Camion>
        {
            new Camion
            {
                Id = 1,
                Patente = "VJ8427",
                Marca = "Freightliner",
                Modelo = "FLD 120",
                Ano = 2003,
                Tipo = "Tracto",
                Color = "Azul",
                Capacidad = "30 Ton",
                Motor = "Detroit Diesel Series 60",
                Caballos = "430 HP",
                Cilindrada = "12.7 L",
                Transmision = "Eaton Fuller 18 velocidades",
                FechaRevisionTecnica = new DateTime(2026, 1, 1),
                FechaPermisoCirculacion = new DateTime(2026, 3, 31),
                FechaSeguroObligatorio = new DateTime(2026, 3, 31),
                RevisionAlDia = true,
                PermisoAlDia = true,
                SeguroAlDia = true,
            },
            new Camion
            {
                Id = 2,
                Patente = "BRDL72",
                Marca = "Freightliner",
                Modelo = "Argosy",
                Ano = 2009,
                Tipo = "Tracto",
                Color = "Blanco",
                Capacidad = "30 Ton",
                Motor = "Detroit Diesel Series 60",
                Caballos = "430 HP",
                Cilindrada = "12.7 L",
                Transmision = "Eaton Fuller 18 velocidades",
                FechaRevisionTecnica = new DateTime(2026, 1, 1),
                FechaPermisoCirculacion = new DateTime(2026, 3, 31),
                FechaSeguroObligatorio = new DateTime(2026, 3, 31),
                RevisionAlDia = true,
                PermisoAlDia = true,
                SeguroAlDia = true,
            },
            new Camion
            {
                Id = 3,
                Patente = "TG5551",
                Marca = "Volskwagen",
                Modelo = "Worker 15-180",
                Ano = 2001,
                Tipo = "Doble Puente",
                Color = "Blanco",
                Capacidad = "15 Ton",
                Motor = "Diésel MWM 6.10 TCA",
                Caballos = "180 HP",
                Cilindrada = "6.1 L",
                Transmision = "Eaton Fuller 5 velocidades",
                FechaRevisionTecnica = new DateTime(2026, 1, 1),
                FechaPermisoCirculacion = new DateTime(2026, 3, 31),
                FechaSeguroObligatorio = new DateTime(2026, 3, 31),
                RevisionAlDia = true,
                PermisoAlDia = true,
                SeguroAlDia = true,
            },
            new Camion
            {
                Id = 4,
                Patente = "XY9353",
                Marca = "International",
                Modelo = "9800i",
                Ano = 2004,
                Tipo = "Tracto",
                Color = "Blanco",
                Capacidad = "30 Ton",
                Motor = "Cummins ISM",
                Caballos = "400 HP",
                Cilindrada = "10.8 L",
                Transmision = "Eaton Fuller 18 velocidades",
                FechaRevisionTecnica = new DateTime(2026, 1, 1),
                FechaPermisoCirculacion = new DateTime(2026, 3, 31),
                FechaSeguroObligatorio = new DateTime(2026, 3, 31),
                RevisionAlDia = false,
                PermisoAlDia = true,
                SeguroAlDia = true,
            },
            new Camion
            {
                Id = 5,
                Patente = "WR8495",
                Marca = "International",
                Modelo = "9800i",
                Ano = 2006,
                Tipo = "Tracto",
                Color = "Blanco",
                Capacidad = "30 Ton",
                Motor = "Cummins ISM",
                Caballos = "400 HP",
                Cilindrada = "10.8 L",
                Transmision = "Eaton Fuller 18 velocidades",
                FechaRevisionTecnica = new DateTime(2026, 1, 1),
                FechaPermisoCirculacion = new DateTime(2026, 3, 31),
                FechaSeguroObligatorio = new DateTime(2026, 3, 31),
                RevisionAlDia = false,
                PermisoAlDia = true,
                SeguroAlDia = true,
            },
            new Camion
            {
                Id = 6,
                Patente = "YS6755",
                Marca = "International",
                Modelo = "9800i",
                Ano = 2004,
                Tipo = "Tracto",
                Color = "Blanco",
                Capacidad = "30 Ton",
                Motor = "Cummins ISM",
                Caballos = "380 HP",
                Cilindrada = "10.8 L",
                Transmision = "Eaton Fuller 13 velocidades",
                FechaRevisionTecnica = new DateTime(2026, 1, 1),
                FechaPermisoCirculacion = new DateTime(2026, 3, 31),
                FechaSeguroObligatorio = new DateTime(2026, 3, 31),
                RevisionAlDia = false,
                PermisoAlDia = true,
                SeguroAlDia = true,
            },
            new Camion
            {
                Id = 7,
                Patente = "VZ9625",
                Marca = "Volswagen",
                Modelo = "Worker 17-220",
                Ano = 2003,
                Tipo = "Doble Puente",
                Color = "Blanco",
                Capacidad = "15 Ton",
                Motor = "Cummins C8.3",
                Caballos = "220 HP",
                Cilindrada = "8.3 L",
                Transmision = "Eaton Fuller 6 velocidades",
                FechaRevisionTecnica = new DateTime(2026, 1, 1),
                FechaPermisoCirculacion = new DateTime(2026, 3, 31),
                FechaSeguroObligatorio = new DateTime(2026, 3, 31),
                RevisionAlDia = false,
                PermisoAlDia = true,
                SeguroAlDia = true,
            },
            new Camion
            {
                Id = 8,
                Patente = "WT7109",
                Marca = "Volswagen",
                Modelo = "Worker 17-210",
                Ano = 2003,
                Tipo = "Doble Puente",
                Color = "Blanco",
                Capacidad = "15 Ton",
                Motor = "Cummins C8.3",
                Caballos = "210 HP",
                Cilindrada = "8.3 L",
                Transmision = "Eaton Fuller 6 velocidades",
                FechaRevisionTecnica = new DateTime(2026, 1, 1),
                FechaPermisoCirculacion = new DateTime(2026, 3, 31),
                FechaSeguroObligatorio = new DateTime(2026, 3, 31),
                RevisionAlDia = false,
                PermisoAlDia = true,
                SeguroAlDia = true,
            },
            new Camion
            {
                Id = 9,
                Patente = "CHBW69",
                Marca = "Volswagen",
                Modelo = "9-150",
                Ano = 2010,
                Tipo = "Camion",
                Color = "Blanco",
                Capacidad = "6 Ton",
                Motor = "Cummins Interact 4.0 electrónico",
                Caballos = "150 HP",
                Cilindrada = "4.0 L",
                Transmision = "Eaton Fuller 5 velocidades",
                FechaRevisionTecnica = new DateTime(2026, 1, 1),
                FechaPermisoCirculacion = new DateTime(2026, 3, 31),
                FechaSeguroObligatorio = new DateTime(2026, 3, 31),
                RevisionAlDia = false,
                PermisoAlDia = true,
                SeguroAlDia = true,
            }
        };

        return Ok(Camiones);
    }
}