# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Deploy Angular app to Azure Web App - transportesorellana-web

on:
  push:
    branches:
      - Dev
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_F7D8B3DCB5604054935516E78C535544 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_A4F1FFDE3ABF4058AB4FD43757253CDD }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_16DF809F415245F78784F93266F0B234 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'transportesorellana-web'
          slot-name: 'Production'
          package: frontend/TransportesOrellanaSpa.Web/azure
